# permissions for end users to view verifyapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifyapp-viewer-role
rules:
- apiGroups:
  - apps.ibm.com
  resources:
  - verifyapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ibm.com
  resources:
  - verifyapps/status
  verbs:
  - get
