# permissions for end users to edit verifyapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifyapp-editor-role
rules:
- apiGroups:
  - apps.ibm.com
  resources:
  - verifyapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ibm.com
  resources:
  - verifyapps/status
  verbs:
  - get
